name: Build and Push Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image [true|false]'
        required: false
        default: 'false'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event.inputs.push != 'false' }}
        platforms: linux/amd64
        tags: ghcr.io/tigattack/vmware_exporter:main
